image: node:20.12.1

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - node -v
    - npm -v
    - pnpm -v
    - pwd
  script:
    - pnpm install
    - pnpm build

deploy:
  stage: deploy
  before_script: 
    - pwd
  script:
    - ssh gitlab_deploy@deploy.inner.tinyplan.cn "cd /usr/local/nginx/html && rm -rf portal/*"
    - scp -r dist/* gitlab_deploy@deploy.inner.tinyplan.cn:/usr/local/nginx/html/portal
    # - ssh gitlab_deploy@deploy.inner.tinyplan.cn "cd /usr/local/nginx/html && chown -R gitlab_deploy:nginx portal/* && chown -R 774 portal/*"